version: '3'
services:
  auto_zapusk:
    build: .
    ports:
      - '7777:7777'
    depends_on:
      - influxDB

  mosquitto:
    image: ansi/mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883

  influxDB:
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=eldata
