version: '3'
services:
  auto_zapusk:
    build: .
    ports:
      - '7777:7777'
    depends_on:
      - influxDB

  influxDB:
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=eldata
